### ISSUE TITLE
Feature Request: header support

### ISSUE THREAD

**Issue by jregeimbal** [moshensky/html-to-pdf-converter#6]
Hi There,

I came across your project and am quite impressed!  Puppeteer/Headless Chrome is def the way to go for PDF gen.  I am planning to use your lib for a pdf generating micro service.   The footer generation works great and I'm curious what your roadmap is for implementing support for page headers?

Thanks for the great work!

**Comment by moshensky** [comment]
@jregeimbal puppeteer added header/footer api https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions as of latest versions. This lib could be useful still if you need to have different headers/footers on different pages and keep page numbers intact, if not probably going with puppeteer alone is a better option. You should be able already to use html header/footer and plain text for footer. If you need same plain text option for header let me know and I will add it.
